# -*- coding: utf-8 -*-
"""load_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dMC_k22ADjyKbvtJpNdNUXou-NWpEAIi
"""

#pip install boto3

import boto3
import json
from boto3 import client as boto3_client

access_key='xyz'
secret_access_key='abc'

# Establishing AWS session and DynamoDB resource connection
aws_session = boto3.Session(aws_access_key_id=access_key, aws_secret_access_key=secret_access_key, region_name='us-east-1')
dynamo_resource = aws_session.resource('dynamodb')
dynamo_table = dynamo_resource.Table('Student_data')

# Loading student data from JSON file
json_records = ""
with open('/content/drive/MyDrive/cse546-project-lambda/student_data.json','r') as datafile:
    json_records = json.load(datafile)

record_count = 0
# Iterating through records and adding an 'index' field
for record in json_records:
    record['index'] = record_count
    print(record)
    # Putting the record into the DynamoDB table
    response = dynamo_table.put_item(Item=record)
    record_count += 1

# Copying the encoding file to the input S3 bucket
s3_client = boto3_client('s3', region_name='us-east-1', aws_access_key_id=access_key, aws_secret_access_key=secret_access_key)
input_bucket_name = 'inputbucket-lasnubes'

s3_client.upload_file('/content/drive/MyDrive/cse546-project-lambda/encoding', input_bucket_name, 'encoding')

